//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.Composition;
using System.Linq;
using EstarDXBase.Infrastructure.EFData;
using EstarDXBase.Domain.Models.Oragnization;
using EstarDXBase.Core.Service.Authen;
using EstarDXBase.Core.Repository.Oragnization;
using EstarDXBase.Infrastructure.Tool;
using EstarDXBase.Web.Models.Oragnization.SystemDepartments;

namespace EstarDXBase.Core.Service.Oragnization.Impl
{
	/// <summary>
    /// 服务操作层实现 —— SystemDepartment
    /// </summary>
    [Export(typeof(ISystemDepartmentService))]
    public class SystemDepartmentService : CoreServiceBase, ISystemDepartmentService
    {
        #region 属性
        [Import]
        public ISystemDepartmentRepository SystemDepartmentRepository { get; set; }
        [Import]
        public ISystemOragnizationRepository SystemOragnizaitonRepository { get; set; }

        public IQueryable<SystemDepartment> SystemDepartments
        {
            get { return SystemDepartmentRepository.Entities; }
        }
        #endregion
        #region 公共方法
     

        public OperationResult Insert(SystemDepartmentsModel model)
        {

            var entity = new SystemDepartment
            {
                Name = model.Name,
                ParentID = model.ParentId,
                CreateId = model.CreateId,
                CreateBy = model.CreateBy,
                CreateTime = DateTime.Now,
                ModifyId = model.ModifyId,
                ModifyBy = model.ModifyBy,
                ModifyTime = DateTime.Now,
                OrderSort = model.OrderSort,
                SystemOragnizationID=model.SystemOragnizationID,
                Enabled = model.Enabled
                
            };
            SystemDepartmentRepository.Insert(entity);
            return new OperationResult(OperationResultType.Success, "添加成功");
        }

        public OperationResult Update(SystemDepartmentsModel model)
        {
            var entity = SystemDepartments.First(t => t.Id == model.Id);
            entity.Name = model.Name;
            entity.ParentID = model.ParentId;
            entity.OrderSort = model.OrderSort;
            entity.Enabled = model.Enabled;
            entity.ModifyId = model.ModifyId;
            entity.ModifyBy = model.ModifyBy;
            entity.ModifyTime = model.ModifyTime;
            entity.SystemOragnizationID = model.SystemOragnizationID;
            SystemDepartmentRepository.Update(entity);
            return new OperationResult(OperationResultType.Success, "更新成功");
        }

        public OperationResult Delete(int Id)
        {
            var model = SystemDepartments.FirstOrDefault(t => t.Id == Id);
            model.IsDeleted = true;
            SystemDepartmentRepository.Delete(model);
            return new OperationResult(OperationResultType.Success, "删除成功");
        }
        #endregion
    
    
    }
}
