//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

using EstarDXBase.Infrastructure.EFData;
using EstarDXBase.Domain.Models.Oragnization;


namespace EstarDXBase.Domain.Data.Mapping.Oragnization
{
    /// <summary>
    /// 数据表映射 —— EduType
    /// </summary>    
	partial class EduTypeMap
    {
        /// <summary>
		/// 映射配置
		/// </summary>
        partial void EduTypeMapAppend()
        {
			// Primary Key
            this.HasKey(t => t.Id);
            // Properties
            this.Property(t => t.Name)
                .HasMaxLength(50);
            this.Property(t => t.Description)
                .HasMaxLength(100);
            this.Property(t => t.CreateBy)
                .HasMaxLength(50);
            this.Property(t => t.ModifyBy)
                .HasMaxLength(50);

            
            // Table & Column Mappings
            this.ToTable("Common_Edu_EduType");
            this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(t => t.Name).HasColumnName("Name");
             this.Property(t => t.Enabled).HasColumnName("Enabled");
            this.Property(t => t.Description).HasColumnName("Description");
            this.Property(t => t.OrderSort).HasColumnName("OrderSort");
            this.Property(t => t.CreateId).HasColumnName("CreateId");
            this.Property(t => t.CreateBy).HasColumnName("CreateBy");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.ModifyId).HasColumnName("ModifyId");
            this.Property(t => t.ModifyBy).HasColumnName("ModifyBy");
            this.Property(t => t.ModifyTime).HasColumnName("ModifyTime");
            // Relation
        }

		
    }
}
