//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

using EstarDXBase.Infrastructure.EFData;
using EstarDXBase.Domain.Models.Oragnization;


namespace EstarDXBase.Domain.Data.Mapping.Oragnization
{
    /// <summary>
    /// 数据表映射 —— SystemOragnization
    /// </summary>    
	partial class SystemOragnizationMap
    {
        /// <summary>
		/// 映射配置
		/// </summary>
        partial void SystemOragnizationMapAppend()
        {
			// Primary Key
            this.HasKey(t => t.Id);
            // Properties
            this.Property(t => t.Name)
                .HasMaxLength(50);

            this.Property(t => t.LayerFlag)
                .HasMaxLength(50);

            this.Property(t => t.StandardID)
                .HasMaxLength(100);

            this.Property(t => t.Adderss)
                .HasMaxLength(100);

            this.Property(t => t.ZipCode)
             .HasMaxLength(10);

            this.Property(t => t.Phone)
             .HasMaxLength(30);

            this.Property(t => t.Email)
             .HasMaxLength(30);

            this.Property(t => t.Contact)
             .HasMaxLength(30);

            this.Property(t => t.ContactPost)
            .HasMaxLength(30);

            this.Property(t => t.CreateBy)
                .HasMaxLength(50);

            this.Property(t => t.ModifyBy)
                .HasMaxLength(50);
            // Properties
            
            // Table & Column Mappings
            this.ToTable("Common_Edu_SystemOragnization");
            this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(t => t.Name).HasColumnName("Name");
            this.Property(t => t.ParentID).HasColumnName("ParentID");
            this.Property(t => t.LayerFlag).HasColumnName("LayerFlag");
            this.Property(t => t.StandardID).HasColumnName("StandardID");
            this.Property(t => t.Adderss).HasColumnName("Adderss");
            this.Property(t => t.ZipCode).HasColumnName("ZipCode");
            this.Property(t => t.Phone).HasColumnName("Phone");
            this.Property(t => t.Email).HasColumnName("Email");
            this.Property(t => t.Contact).HasColumnName("Contact");
            this.Property(t => t.ContactPost).HasColumnName("ContactPost");
            this.Property(t => t.IsLocking).HasColumnName("IsLocking");
            this.Property(t => t.OrderSort).HasColumnName("OrderSort");
            this.Property(t => t.CreateId).HasColumnName("CreateId");
            this.Property(t => t.CreateBy).HasColumnName("CreateBy");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.ModifyId).HasColumnName("ModifyId");
            this.Property(t => t.ModifyBy).HasColumnName("ModifyBy");
            this.Property(t => t.ModifyTime).HasColumnName("ModifyTime");
            this.Property(t => t.Enabled).HasColumnName("Enabled");
            this.Property(t => t.EduTypeID).HasColumnName("EduTypeID");
            // Relation

            this.HasRequired(t => t.EduType).WithMany(d => d.SystemOragnization).HasForeignKey(f => f.EduTypeID).WillCascadeOnDelete(true);

        }

		
    }
}
