//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
//------------------------------------------------------------------------------

using System;

using EstarDXBase.Infrastructure.EFData;
using EstarDXBase.Domain.Models.Oragnization;
using EstarDXBase.Infrastructure.Tool;
using EstarDXBase.Web.Models.Oragnization.EduType;
using System.Linq;


namespace EstarDXBase.Core.Service.Oragnization
{
	/// <summary>
    /// 仓储操作层接口 —— EduType
    /// </summary>
    public interface IEduTypeService
    {
        #region 属性

        IQueryable<EduType> EduTypes { get; }

        #endregion
         OperationResult Insert(EduTypeModel model);
         OperationResult Update(EduTypeModel model);

         /// <summary>
         /// 逻辑删除
         /// </summary>
         /// <param name="Id"></param>
         /// <returns></returns>
         OperationResult Delete(int Id);
    }
}
